[package]
name = "gp_tool"
version = "1.0.2"
authors = ["PikminGuts92"]
edition = "2021"

[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
log = "0.4.17"
praise_mod_lib = { path = "../praise_mod_lib" }
simplelog = "0.12.0"
thiserror = "1.0.31"
