[package]
name = "gp_tool"
version = "1.0.1"
authors = ["PikminGuts92"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
log = "0.4.11"
praise_mod_lib = { path = "../praise_mod_lib" }
simplelog = "0.10.0"
thiserror = "1.0.20"