[package]
name = "pack_maker"
version = "1.0.2"
authors = ["PikminGuts92"]
edition = "2021"

[dependencies]
eframe = "0.17.0"
image = { version = "0.24.0", default-features = false, features = [ "png" ] }
native-dialog = "0.6.1"
praise_mod_lib = { path = "../praise_mod_lib" }