[package]
name = "praise_mod_lib"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2018"

[dependencies]
fon = "0.5.0"
ghakuf = "0.5.6"
image = "0.23.12"
lewton = "0.10.1"
log = "0.4.11"
nom = "6.1.2"
rayon = "1.5.0"
rust-ini = "0.17.0"
thiserror = "1.0.20"
walkdir = "2.3.1"

[dependencies.vorbis-encoder]
git = "https://github.com/Hossein-Noroozpour/vorbis-encoder-rs"