[package]
name = "praise_mod_lib"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2018"

[dependencies]
ghakuf = "0.5.6"
log = "0.4.11"
rust-ini = "0.16.0"
thiserror = "1.0.20"
walkdir = "2.3.1"