[package]
name = "praise_mod_lib"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2018"

[dependencies]
ghakuf = "0.5.6"
image = "0.23.12"
log = "0.4.11"
nom = "6.0.1"
ogg = "0.7.1"
rust-ini = "0.16.0"
symphonia = "0.1.0"
thiserror = "1.0.20"
walkdir = "2.3.1"

[dependencies.vorbis-encoder]
git = "https://github.com/PikminGuts92/vorbis-encoder-rs"