on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  build_release:
    name: Build Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Zip files
        shell: bash
        working-directory: $GITHUB_WORKSPACE
        run: .github/scripts/package_files.sh -b $GITHUB_WORKSPACE/target/release -o $GITHUB_WORKSPACE/build -z "praise-mod-ci-$GITHUB_SHA.zip"
      - uses: actions/upload-artifact@v2
        with:
          name: praise-mod-ci-$GITHUB_SHA.zip
          path: $GITHUB_WORKSPACE/build/praise-mod-ci-$GITHUB_SHA.zip